# Generated by Django 4.1.5 on 2023-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
