# Generated by Django 4.1.5 on 2023-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_pmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Year',
            new_name='year',
        ),
    ]
