# Generated by Django 4.1.5 on 2023-04-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_year_product_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
