# Generated by Django 4.1.5 on 2023-04-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
