# Generated by Django 4.1.5 on 2023-04-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Available',
            field=models.BooleanField(default=False),
        ),
    ]
