# Generated by Django 4.1.5 on 2023-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Available',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
