# Generated by Django 4.1.5 on 2023-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_table',
            name='char_f',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
